package br.com.supportcomm.virtualgoodscore.constantes;

public enum StatusType {
	
	FLOW_START,						
	
	PROCESS_TRANSACTION,
	
	ASK_PARTNER_AUTHORIZATION,
	ASK_OPTION_IN,
	
	WAIT_PARTNER_AUTHORIZATION,
	WAIT_OPTION_IN_ANSWER,
	
	PROCESS_BILLING,					
	PROCESS_TRANSACTION_RESPONSE,	
	PROCESS_SEND_VOUCHER,
	GENERATE_VOUCHER,
	SEND_OPTION_IN,
	SEND_VOUCHER,
	SEND_MT_MESSAGE,
	
	FLOW_END,

}
