package br.com.supportcomm.virtualgoods.enums;

public enum VoucherStatus {

	VOUCHER_NOT_CONSUMED,
	VOUCHER_ALREADY_CONSUMED,
	VOUCHER_NOT_FOUND,
	VOUCHER_SET_TO_CONSUMED_SUCESSFULLY,
	ERROR_WHILE_UPDATING_VOUCHER_STATUS,
	ERROR_WHILE_GETTING_VOUCHER_STATUS

}
